using OpenTK;

namespace Force3D
{
    /// <summary>
    /// Class used for time functions, such as monitoring time since the app was started, and length of the last frame in seconds
    /// </summary>
    class Time
    {
        /// <summary>
        /// Length of the last frame in seconds
        /// </summary>
        public static float FrameTime;
        /// <summary>
        /// Total time since the app was started
        /// </summary>
        public static float GameTime;

        /// <summary>
        /// Called every frame of the game
        /// </summary>
        /// <param name="e">FrameEventArgs generated by OpenTK</param>
        public static void OnFrame(FrameEventArgs e)
        {
            FrameTime = (float)e.Time;
            GameTime += FrameTime;
        }
    }
}
